$engine: 3
$onesync: on
name: CFX Default FiveM
description: Recipe for the base resources required to run a minimal FiveM server.

tasks: 
  # Download default CFX resources
    - action: download_file
    src: https://github.com/bubuseb/cfx-server-data/archive/refs/heads/main.zip
